/* users table */

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL
);

ALTER TABLE users
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS roles (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

ALTER TABLE users
ADD COLUMN username VARCHAR(255) NOT NULL;

/* create version table */

CREATE TABLE IF NOT EXISTS versions (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  estado VARCHAR(50) DEFAULT 'borrador',
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  usuario_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

/* create version history table */

CREATE TABLE IF NOT EXISTS version_history (
  id SERIAL PRIMARY KEY,
  version_id INTEGER NOT NULL REFERENCES versions(id) ON DELETE CASCADE,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  accion VARCHAR(50) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
